# Generated by Django 2.2.7 on 2019-11-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('unit_id', models.IntegerField(unique=True)),
                ('bedrooms', models.IntegerField()),
                ('suits', models.IntegerField()),
                ('parking_spots', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('complex_fee', models.IntegerField()),
                ('property_tax', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('current_phase', models.CharField(max_length=50)),
                ('power_generator', models.BooleanField()),
                ('gourmet', models.BooleanField()),
                ('green_area', models.BooleanField()),
                ('grill', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('heated_pool', models.BooleanField()),
                ('kids', models.BooleanField()),
                ('party_room', models.BooleanField()),
                ('play_game', models.BooleanField()),
                ('playground', models.BooleanField()),
                ('pool', models.BooleanField()),
                ('court', models.BooleanField()),
                ('street_name', models.CharField(max_length=50)),
                ('street_type', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
                ('lat', models.CharField(max_length=30)),
                ('lng', models.CharField(max_length=30)),
            ],
        ),
    ]
