# Generated by Django 2.2.7 on 2019-12-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(db_index=True, max_length=50)),
                ('places', models.ManyToManyField(related_name='favorite', to='onboarding.Place')),
            ],
        ),
    ]
